CREATE DATABASE Vozila;
USE Vozila;


CREATE TABLE VehicleMake(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(25) NOT NULL,
Abrv NVARCHAR(10) NOT NULL
);

CREATE TABLE VehicleModel(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
MakeId INT NOT NULL FOREIGN KEY REFERENCES VehicleMake(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
Name NVARCHAR(25) NOT NULL,
Abrv NVARCHAR(10) NOT NULL
);